package ru.koss.lib

import ru.koss.lib.tests.ShowPromoExperiment
import ru.koss.lib.tests.ButtonTextExperiment

/**
* THIS CODE WAS AUTOGENERATED
* YOU CANNOT MODIFY THIS FILE.
*/
interface ABRepository {
open fun getShowPromoExperiment(): ShowPromoExperiment
open fun getButtonTextExperiment(): ButtonTextExperiment
}