package ru.koss.lib

import ru.koss.lib.config.ABConfig
import ru.koss.lib.tests.ShowPromoExperiment
import ru.koss.lib.tests.ButtonTextExperiment
/**
* THIS CODE WAS AUTOGENERATED
* YOU CANNOT MODIFY THIS FILE.
*/
class ABRepositoryImpl(private val version: String, private val config: ABConfig) : ABRepository {

init {
if(version != "1.0") {
throw IllegalStateException("Please check your AB testing configuration seems like you forgot to update code with new tests changes !")
}
}

override fun getShowPromoExperiment(): ShowPromoExperiment {
val value = config.getValue(ShowPromoExperiment.DEF_EXPERIMENT.getExperimentKey(),"")
return when (value) {
ShowPromoExperiment.A_EXPERIMENT.getExperimentValue() -> ShowPromoExperiment.A_EXPERIMENT
else -> ShowPromoExperiment.DEF_EXPERIMENT
}
}
override fun getButtonTextExperiment(): ButtonTextExperiment {
val value = config.getValue(ButtonTextExperiment.DEF_EXPERIMENT.getExperimentKey(),"")
return when (value) {
ButtonTextExperiment.A_EXPERIMENT.getExperimentValue() -> ButtonTextExperiment.A_EXPERIMENT
ButtonTextExperiment.B_EXPERIMENT.getExperimentValue() -> ButtonTextExperiment.B_EXPERIMENT
ButtonTextExperiment.C_EXPERIMENT.getExperimentValue() -> ButtonTextExperiment.C_EXPERIMENT
else -> ButtonTextExperiment.DEF_EXPERIMENT
}
}

}